apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hyfbb15lf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hyfbb15lf-java-springboot-gitops